In [9]:
# These are all the modules we'll be using later. Make sure you can import them
# before proceeding further.
from __future__ import print_function
import numpy as np
import tensorflow as tf


arr = np.array([1,2,3,4,5])
print(arr)
print(arr[:, None])

print('ok')



arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print('\n arr2d[0, 0]: \n', arr2d[0, 0])
print('\n arr2d[:2]: \n', arr2d[:2])
print('\n arr2d[:2, 1:]: \n', arr2d[:2, 1:])

# select a column
print('\n arr2d[:, 0]: \n', arr2d[:, 0])



[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]
 [5]]
ok

 arr2d[0, 0]: 
 1

 arr2d[:2]: 
 [[1 2 3]
 [4 5 6]]

 arr2d[:2, 1:]: 
 [[2 3]
 [5 6]]

 arr2d[:, 0]: 
 [1 4 7]


In [32]:
arr3d = np.array([
    [
        [1, 2, 3], [4, 5, 6]
    ], 
    [
        [7, 8, 9], [10, 11, 12]
    ]
])
print('\narr3d[0, 1]:\n', arr3d[0, 1])


arr3d[0, 1]:
 [4 5 6]


In [55]:
data = np.random.randn(7, 2)
print('\n', data)

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print('\n', names)

# create bool array
bobs = (names == 'Bob').astype(np.int32)
print('\n', bobs)

# use bool array to extract data
bobs2 = data[names == 'Bob', 0:]
print('\n', bobs2)

# use negated bool array to extract data
bobs3 = data[names != 'Bob', 0:]
print('\n', bobs3)

# use negated bool array to extract data (a different method)
bobs4 = data[~(names == 'Bob'), 0:]
print('\n', bobs4)

# use condition mask to create bool array
mask = (names == 'Bob') | (names == 'Will')
print('\n', mask)

# assign all values smaller than 0 to 0
data[data < 0] = 0
print(data)


 [[-0.88097116  0.52152081]
 [ 1.0765528   0.83391059]
 [ 0.08489721  0.93130695]
 [ 0.14443681 -0.52413798]
 [ 0.35768223 -0.40569693]
 [ 2.11197058  0.67812462]
 [-1.46873503  0.36748657]]

 ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']

 [1 0 0 1 0 0 0]

 [[-0.88097116  0.52152081]
 [ 0.14443681 -0.52413798]]

 [[ 1.0765528   0.83391059]
 [ 0.08489721  0.93130695]
 [ 0.35768223 -0.40569693]
 [ 2.11197058  0.67812462]
 [-1.46873503  0.36748657]]

 [[ 1.0765528   0.83391059]
 [ 0.08489721  0.93130695]
 [ 0.35768223 -0.40569693]
 [ 2.11197058  0.67812462]
 [-1.46873503  0.36748657]]

 [ True False  True  True  True False False]
[[ 0.          0.52152081]
 [ 1.0765528   0.83391059]
 [ 0.08489721  0.93130695]
 [ 0.14443681  0.        ]
 [ 0.35768223  0.        ]
 [ 2.11197058  0.67812462]
 [ 0.          0.36748657]]


In [75]:
arr = np.empty((8, 4))

for i in range(8):
    arr[i] = i

print('\n', arr)

# select multiple rows (use nested array)
print('\n', arr[[4, 3, 6]])
# equivalent to: print('\n', arr[[4, 3, 6], :])

print('\n', arr[[-3, -5, -7]])

arr2 = np.arange(32).reshape((8, 4))

print('\n', arr2)

# select (1, 0), (5, 3), (7, 1), and (2, 2)
print('\n', arr2[[1, 5, 7, 2], [0, 3, 1, 2]])

# select rows 1,5,7,2; rearrange column indices to 0, 3, 1, 2
print('\n', arr2[[1, 5, 7, 2]][:, [0, 3, 1, 2]])


 [[ 0.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 2.  2.  2.  2.]
 [ 3.  3.  3.  3.]
 [ 4.  4.  4.  4.]
 [ 5.  5.  5.  5.]
 [ 6.  6.  6.  6.]
 [ 7.  7.  7.  7.]]

 [[ 4.  4.  4.  4.]
 [ 3.  3.  3.  3.]
 [ 6.  6.  6.  6.]]

 [[ 5.  5.  5.  5.]
 [ 3.  3.  3.  3.]
 [ 1.  1.  1.  1.]]

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

 [ 4 23 29 10]

 [[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [91]:
arr = np.arange(15).reshape((3, 5))
print('\n', arr)
print('\n', arr.T)
print('\n', np.dot(arr.T, arr))

arr = np.arange(16).reshape((2, 2, 4))
print('\ntranspose')
print('\n', arr)

# 1, 2, 0 represents dimension 0, 2, 1 here, 
# so here 3rd dimension(2) is swapped with 2nd dimension(1)
arr = arr.transpose((1, 2, 0))
print('\n', arr, arr.shape)

x = np.ones((1, 2, 3))
print('\n', x.T.shape)


 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]

 [[125 140 155 170 185]
 [140 158 176 194 212]
 [155 176 197 218 239]
 [170 194 218 242 266]
 [185 212 239 266 293]]

transpose

 [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]

 [[[ 0  8]
  [ 1  9]
  [ 2 10]
  [ 3 11]]

 [[ 4 12]
  [ 5 13]
  [ 6 14]
  [ 7 15]]] (2, 4, 2)

 (3, 2, 1)


In [18]:
arr = np.random.randn(4, 4)
print('\n', np.where(arr > 0, 2, arr))
print('\n', np.where(arr > 0, 2, -2))

arr = np.random.randn(2,2)
print('\n', arr)

arr.sort(1)
print('\n', arr)


 [[ 2.          2.          2.          2.        ]
 [ 2.          2.          2.          2.        ]
 [-0.13605061 -0.45547502  2.          2.        ]
 [ 2.         -0.50194995 -0.02388736  2.        ]]

 [[ 2  2  2  2]
 [ 2  2  2  2]
 [-2 -2  2  2]
 [ 2 -2 -2  2]]

 [[ 0.44197515  0.26792203]
 [ 0.91827181 -2.31101646]]

 [[ 0.26792203  0.44197515]
 [-2.31101646  0.91827181]]
